name: Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0

      - name: Prettify code
      # Ref: https://github.com/marketplace/actions/prettier-action
        uses: creyD/prettier_action@v4.3
        with:
          # Prettier CLI options: https://prettier.io/docs/en/cli
          prettier_options: --write . --config ./.prettierrc.json --ignore-path frontend/.prettierignore --ignore-path backend/.prettierignore 
          same_commit: True
